CREATE TABLE [dbo].[LOGS] (
    [ID]             INT      IDENTITY (1, 1) NOT NULL,
    [CREATE_DATE]    DATETIME NOT NULL,
    [MODIFY_DATE]    DATETIME NULL,
    [CREATED_BY]     INT      NOT NULL,
    [MODIFICATED_BY] INT      NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_LOG] FOREIGN KEY ([CREATED_BY]) REFERENCES [dbo].[PERDORUES] ([perdorues_id]),
    CONSTRAINT [FK_LOG_MODIFIKO] FOREIGN KEY ([MODIFICATED_BY]) REFERENCES [dbo].[PERDORUES] ([perdorues_id])
);

