//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationVakti_Im.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG
    {
        public int ID { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public int CREATED_BY { get; set; }
        public Nullable<int> MODIFICATED_BY { get; set; }
    
        public virtual PERDORUE PERDORUE { get; set; }
        public virtual PERDORUE PERDORUE1 { get; set; }
    }
}
