//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationVakti_Im.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERDORUE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERDORUE()
        {
            this.GATIMs = new HashSet<GATIM>();
            this.GATIMs1 = new HashSet<GATIM>();
            this.LOGS = new HashSet<LOG>();
            this.LOGS1 = new HashSet<LOG>();
            this.POROSIs = new HashSet<POROSI>();
            this.POROSIs1 = new HashSet<POROSI>();
        }
    
        public int perdorues_id { get; set; }
        public string emri { get; set; }
        public string mbiemri { get; set; }
        public string telefon { get; set; }
        public bool aktiv { get; set; }
        public string username { get; set; }
        public System.DateTime krijimPerdorues { get; set; }
        public Nullable<System.DateTime> modifikimPerdoruesi { get; set; }
        public int rol_id { get; set; }
        public string passwordi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GATIM> GATIMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GATIM> GATIMs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG> LOGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG> LOGS1 { get; set; }
        public virtual ROLI ROLI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POROSI> POROSIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POROSI> POROSIs1 { get; set; }
    }
}
