//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationVakti_Im.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POROSI_ITEM
    {
        public int porosi_id { get; set; }
        public int sasia { get; set; }
        public int gatim_id { get; set; }
    
        public virtual GATIM GATIM { get; set; }
        public virtual POROSI POROSI { get; set; }
    }
}
